-- SECTION 1 : Platform Overview
-- How much total revenue was generated by the platform?
select sum(payment_value) as total_revenue from olist_order_payments;

-- What is the average order value?
select sum(payment_value)/count(DISTINCT order_id) as average_order_value from olist_order_payments;

-- How many total orders exist on the platform?
select count(DISTINCT order_id) as total_orders from olist_orders;

-- How many unique customers does the platform have?
select count(DISTINCT customer_unique_id) as total_unique_customers from olist_customers;

-- What is the average number of orders per customer?
select count(Distinct o.order_id)/count(distinct c.customer_unique_id) as avg_orders_per_customer from olist_orders o join olist_customers c on o.customer_id = c.customer_id;


-- SECTION 2 : Sales Trends
-- How does revenue change month by month?
select YEAR(o.order_purchase_timestamp) as year, MONTH(o.order_purchase_timestamp) as month, SUM(p.payment_value) as monthly_revenue from olist_orders o join olist_order_payments p on o.order_id = p.order_id group by year,month order by year,month;

-- SECTION 3 : Market and Product Performance
-- Which states generate maximum revenue?

select c.customer_state, sum(p.payment_value) as total_revenue from olist_customers c join olist_orders o on c.customer_id=o.customer_id join olist_order_payments p on  o.order_id=p.order_id group by c.customer_state order by total_revenue DESC;

-- Which products sell the most?
select product_id,count(*) as total_sales from olist_order_items group by product_id order by total_sales DESC LIMIT 10;

-- Which product categories generate the most revenue?
select p.product_category_name, sum(oi.price) as total_revenue from olist_order_items oi join olist_products p on oi.product_id = p.product_id group by p.product_category_name order by total_revenue DESC LIMIT 10;

-- SECTION 4: Logistics
-- What is the average delivery time for orders?
select avg(datediff(order_delivered_customer_date, order_purchase_timestamp)) as avg_delivery_days from olist_orders where order_delivered_customer_date is not NULL;

--  SECTION 5 : Customer Behaviour
-- Which customers spend the most money?
select c.customer_unique_id, sum(p.payment_value) as total_spent from olist_customers c join olist_orders o on c.customer_id=o.customer_id join olist_order_payments p on o.order_id=p.order_id group by c.customer_unique_id order by total_spent DESC LIMIT 10;

-- Which states have the most customers?
select customer_state, count(distinct customer_unique_id) as total_customers from olist_customers group by customer_state order by total_customers DESC;
-- SECTION 6 : Delivery Reliability
-- How many orders were delivered late?
select count(*) as late_deliveries from olist_orders where order_delivered_customer_date > order_estimated_delivery_date;

-- What percentage of deliveries are late?
select count(case when order_delivered_customer_date>order_estimated_delivery_date then 1 end) * 100.0 / count(*) as late_delivery_percentage from olist_orders where order_delivered_customer_date IS NOT NULL;

-- SECTION 7 : Product Pricing Insights
-- Which product categories have the highest average price?
select p.product_category_name, avg(oi.price) as avg_product_price from olist_order_items oi join olist_products p on oi.product_id=p.product_id group by p.product_category_name order by avg_product_price DESC LIMIT 10;

-- SECTION 8: Advanced Operational Insights
-- Which State experiences the longest delivery times?

select c.customer_state, avg(DATEDIFF(o.order_delivered_customer_date, o.order_purchase_timestamp)) as avg_delivery_days from olist_orders o join olist_customers c on o.customer_id = c.customer_id where o.order_delivered_customer_date IS NOT NULL group by c.customer_state order by avg_delivery_days DESC;

-- Which product categories receive the highest number of orders?

Select p.product_category_name, count(*) as total_orders from olist_order_items oi join olist_products p on oi.product_id = p.product_id group by p.product_category_name order by total_orders DESC LIMIT 10;

-- Which months have the highest order volume?
select YEAR(order_purchase_timestamp) as year, MONTH(order_purchase_timestamp) as month, count(*) as total_orders from olist_orders group by year,month order by total_orders DESC;

-- What is the average shipping cost  per order
select avg(freight_value) as avg_shipping_cost from olist_order_items;

-- Which product categories have the highest shipping cost?
select p.product_category_name, avg(oi.freight_value) as avg_shipping_cost  from olist_order_items oi join olist_products p on oi.product_id=p.product_id group by p.product_category_name order by avg_shipping_cost DESC LIMIT 10;

-- Which states generates the Highest shipping cost?
SELECT c.customer_state, AVG(oi.freight_value) as avg_shipping_cost from olist_order_items oi join olist_orders o on oi.order_id=o.order_id join olist_customers c on o.customer_id=c.customer_id group by c.customer_state order by avg_shipping_cost DESC;

-- What is the distribution of orders across product categories?
select p.product_category_name, count(*) as total_orders from olist_order_items oi join olist_products p on oi.product_id=p.product_id group by p.product_category_name order by total_orders DESC;